#!/usr/bin/python
import rospy
from recorder_node.recorder import Recorder


def main():
    rec = Recorder()
    rec.run()

    new_recording = True
    
    while new_recording and not rospy.is_shutdown():
        rospy.loginfo("Please enter the name of the file to store the recording (do not put the path nor the extension):")
        savefile = raw_input()
        while savefile == "" and not rospy.is_shutdown():
            rospy.loginfo("The file name should at least contain one character. Please enter a valid name:")
            savefile = raw_input()
        
        if rospy.is_shutdown(): return

        rospy.loginfo("Press enter to start recording.")
        raw_input()
        rec.start_recording()

        if rospy.is_shutdown(): return

        rospy.loginfo("Recording... Press enter to stop recording.")
        raw_input()
        filepath = rec.stop_recording(savefile)

        if rospy.is_shutdown(): return

        rospy.loginfo("Recorded data saved in " + filepath + ". Record a new demonstration? y/N:")
        resp = raw_input()
        new_recording = (resp == "y")
    rec.stop()

if __name__ == '__main__':
    rospy.init_node('optitrack_recorder')
    main()
